# -*- coding: utf-8 -*-
"""FinalProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oa7_H9dh5AmOjT6kIsr1mfmmi00IWNQu

#สิ่งแวดล้อม

**หัวข้อสิ่งแวดล้อม**

ชื่อกลุ่มน๊อนเอนไหวไหม

6509611684 ณัชชา สุขะเมือง

6509611932 ภัคสิตานัน กรองทอง

6509611957 ภูธเนศ ผณินทรารักษ์

#IMPORT LIBRARY & DATA
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl

from google.colab import drive
drive.mount('/content/drive')

#to use thai font
!wget -q https://github.com/Phonbopit/sarabun-webfont/raw/master/fonts/thsarabunnew-webfont.ttf
mpl.font_manager.fontManager.addfont("thsarabunnew-webfont.ttf")
mpl.rc('font',family="TH Sarabun New",size = '14')

df= pd.read_csv('/content/drive/MyDrive/แบบสำรวจปัญหาเพื่อพัฒนาคุณภาพชีวิตในการศึกษาที่อาคารบรรยายรวมคณะวิทยาศาสตร์-3.csv')
df

df = df.drop(columns=['ประทับเวลา'])

df.columns

"""#Data Visualization

**ส่วนที่1 : ข้อมูลส่วนตัว**

เพศ
"""

# นับจำนวนแต่ละเพศ
gender_counts = df['เพศ'].value_counts()

# กำหนดสีที่ต้องการ
colors = ['#f32f65', '#1b82c5', '#773b87','#f89c25' , '#5ca2d4' , '#98c32b', '#66addb' ]


# Disable LaTeX rendering
plt.rcParams["text.usetex"] = False

# สร้าง Pie Chart
plt.figure(figsize=(8, 8))
plt.pie(gender_counts, labels=gender_counts.index, autopct='%1.1f%%', startangle=140, colors=colors)
plt.title('เพศ', pad=20, fontweight='bold')  # กำหนดชื่อ title และให้ตัวหนา (bold)
plt.axis('equal')  # ทำให้ Pie Chart เป็นวงกลมที่แท้จริง
plt.show()

"""**ส่วนที่2 : ความสะอาด**"""

# เลือกคอลัมน์ 'ตึกไหนบ้างที่มีปัญหาเรื่องความสะอาดของห้องเรียน (เลือกได้หลายข้อ)' เท่านั้น
column_a = df['ตึกไหนบ้างที่มีปัญหาเรื่องความสะอาดของห้องเรียน (เลือกได้หลายข้อ)']

# ลบคำว่า "ไม่มี" ออกจากคอลัมน์ 'ตึกไหนบ้างที่มีปัญหาเรื่องความสะอาดของห้องเรียน (เลือกได้หลายข้อ)'
column_a = column_a[column_a != "ไม่มี"]

# นับจำนวนของแต่ละค่าที่เหลือ
counts = column_a.value_counts()
counts
# แยกแต่ละคอลัมน์ตาม ";" และประกอบเป็นรายการ
building_list = column_a.str.split(';')

# สร้างรายการแต่ละตึก
building_counts = []
for buildings in building_list:
  building_counts.extend(buildings)
building_counts
# นับจำนวนของแต่ละตึก
counts_a = pd.Series(building_counts).value_counts()
counts_a

#กำหนดสีที่ต้องการ
colors = ['#f32f65', '#1b82c5', '#773b87','#f89c25' , '#5ca2d4' , '#98c32b', '#66addb' ]

# แสดงผลลัพธ์เป็นกราฟแท่ง
plt.bar(counts_a.index, counts_a.values,color=colors)
plt.title('ตึกที่มีปัญหาเรื่องความสะอาดของห้องเรียน ')
plt.xlabel('อาคาร')
plt.ylabel('จำนวน')
plt.show()

# นับจำนวนของแต่ละค่าที่เหลือ
counts = column_a.value_counts()

# แยกแต่ละคอลัมน์ตาม ";" และประกอบเป็นรายการ
building_list = column_a.str.split(';')

# สร้างรายการแต่ละตึก
building_counts = []
for buildings in building_list:
    building_counts.extend(buildings)

# นับจำนวนของแต่ละตึก
counts_a = pd.Series(building_counts).value_counts()

# กำหนดสีที่ต้องการ
colors = ['#f32f65', '#1b82c5', '#773b87', '#f89c25', '#5ca2d4', '#98c32b', '#66addb']

# สร้าง Pie Chart และกำหนดสี
fig, ax = plt.subplots(figsize=(8, 8))
wedges, texts, autotexts = ax.pie(counts_a, labels=counts_a.index, autopct='%1.1f%%', startangle=140, colors=colors, textprops=dict(color="Black"))

# ปรับขนาดของตัวอักษรในรายการชื่อ
for text in texts:
    text.set_fontsize(12)

# ปรับขนาดของตัวเลขในรายการชื่อ
for autotext in autotexts:
    autotext.set_fontsize(12)

plt.title('ตึกที่มีปัญหาเรื่องความสะอาดของห้องเรียน',pad=25)
plt.axis('equal')  # ทำให้ Pie Chart เป็นวงกลมที่แท้จริง
plt.show()

# เลือกคอลัมน์ 'ตึกไหนบ้างที่มีปัญหาเรื่องความสะอาดของห้องน้ำ (เลือกได้หลายข้อ)' เท่านั้น
column_b = df['ตึกไหนบ้างที่มีปัญหาเรื่องความสะอาดของห้องน้ำ  (เลือกได้หลายข้อ)']

# ลบคำว่า "ไม่มี" ออกจากคอลัมน์ 'ตึกไหนบ้างที่มีปัญหาเรื่องความสะอาดของห้องเรียน (เลือกได้หลายข้อ)'
column_b = column_b[column_b != "ไม่มี"]

# นับจำนวนของแต่ละค่าที่เหลือ
counts = column_b.value_counts()

# แยกแต่ละคอลัมน์ตาม ";" และประกอบเป็นรายการ
building_list = column_b.str.split(';')

# สร้างรายการแต่ละตึก
building_counts = []
for buildings in building_list:
    building_counts.extend(buildings)

# นับจำนวนของแต่ละตึก
counts_b = pd.Series(building_counts).value_counts()


#กำหนดสีที่ต้องการ
colors = ['#f32f65', '#1b82c5', '#773b87','#f89c25' , '#5ca2d4' , '#98c32b', '#66addb' ]

# แสดงผลลัพธ์เป็นกราฟแท่ง
plt.bar(counts_b.index, counts_b.values, color = colors)
plt.title('ตึกที่มีปัญหาเรื่องความสะอาดของห้องน้ำ ')
plt.xlabel('อาคาร')
plt.ylabel('จำนวน')
plt.show()

# นับจำนวนของแต่ละค่าที่เหลือ
counts = column_b.value_counts()

# แยกแต่ละคอลัมน์ตาม ";" และประกอบเป็นรายการ
building_list = column_b.str.split(';')

# สร้างรายการแต่ละตึก
building_counts = []
for buildings in building_list:
    building_counts.extend(buildings)

# นับจำนวนของแต่ละตึก
counts_b = pd.Series(building_counts).value_counts()

# กำหนดสีที่ต้องการ
colors = ['#f32f65', '#1b82c5', '#773b87','#f89c25' , '#5ca2d4' , '#98c32b', '#66addb' ]

# สร้าง Pie Chart
plt.figure(figsize=(8, 8))
plt.pie(counts_b, labels=counts_b.index, autopct='%1.1f%%', startangle=140, colors=colors)
plt.title('ตึกที่มีปัญหาเรื่องความสะอาดของห้องน้ำ',pad=25)
plt.axis('equal')  # ทำให้ Pie Chart เป็นวงกลมที่แท้จริง
plt.show()

# เลือกคอลัมน์ 'ตึกไหนบ้างที่มีปัญหาเรื่องความสะอาดของห้องอาคาร (เลือกได้หลายข้อ)' เท่านั้น
column_c = df['ตึกไหนบ้างที่มีปัญหาเรื่องความสะอาดของอาคาร  (เลือกได้หลายข้อ)']

# ลบคำว่า "ไม่มี" ออกจากคอลัมน์ 'ตึกไหนบ้างที่มีปัญหาเรื่องความสะอาดของห้องอาคาร (เลือกได้หลายข้อ)'
column_c = column_c[column_c != "ไม่มี"]

# นับจำนวนของแต่ละค่าที่เหลือ
counts = column_c.value_counts()

# แยกแต่ละคอลัมน์ตาม ";" และประกอบเป็นรายการ
building_list = column_c.str.split(';')

# สร้างรายการแต่ละตึก
building_counts = []
for buildings in building_list:
    building_counts.extend(buildings)

# นับจำนวนของแต่ละตึก
counts_c = pd.Series(building_counts).value_counts()

#กำหนดสีที่ต้องการ
colors = ['#f32f65', '#1b82c5', '#773b87','#f89c25' , '#5ca2d4' , '#98c32b', '#66addb' ]

# แสดงผลลัพธ์เป็นกราฟแท่ง
plt.bar(counts_c.index, counts_c.values,color = colors)
plt.title('ตึกที่มีปัญหาเรื่องความสะอาดของห้องอาคาร ')
plt.xlabel('อาคาร')
plt.ylabel('จำนวน')
plt.show()

# นับจำนวนของแต่ละค่าที่เหลือ
counts = column_c.value_counts()

# แยกแต่ละคอลัมน์ตาม ";" และประกอบเป็นรายการ
building_list = column_c.str.split(';')

# สร้างรายการแต่ละตึก
building_counts = []
for buildings in building_list:
    building_counts.extend(buildings)

# นับจำนวนของแต่ละตึก
counts_c = pd.Series(building_counts).value_counts()

# กำหนดสีที่ต้องการ
colors = ['#f32f65', '#1b82c5', '#773b87','#f89c25' , '#5ca2d4' , '#98c32b', '#66addb']

# สร้าง Pie Chart
plt.figure(figsize=(8, 8))
plt.pie(counts_c, labels=counts_c.index, autopct='%1.1f%%', startangle=140, colors=colors)
plt.title('ตึกที่มีปัญหาเรื่องความสะอาดของห้องอาคาร',pad=25)
plt.axis('equal')  # ทำให้ Pie Chart เป็นวงกลมที่แท้จริง
plt.show()

"""**ส่วนที่ 3 : ความปลอดภัย**"""

# เลือกคอลัมน์ 'ตึกไหนที่ทำให้รู้สึกไม่ปลอดภัย  (เลือกได้หลายข้อ)' เท่านั้น
column_d = df['ตึกไหนที่ทำให้รู้สึกไม่ปลอดภัย  (เลือกได้หลายข้อ)']

# ลบคำว่า "ไม่มี" ออกจากคอลัมน์ 'ตึกไหนบ้างที่มีปัญหาเรื่องความสะอาดของห้องอาคาร (เลือกได้หลายข้อ)'
column_d = column_d[column_d != "ไม่มี"]

# นับจำนวนของแต่ละค่าที่เหลือ
counts = column_d.value_counts()

# แยกแต่ละคอลัมน์ตาม ";" และประกอบเป็นรายการ
building_list = column_d.str.split(';')

# สร้างรายการแต่ละตึก
building_counts = []
for buildings in building_list:
    building_counts.extend(buildings)

# นับจำนวนของแต่ละตึก
counts_d = pd.Series(building_counts).value_counts()

#กำหนดสีที่ต้องการ
colors = ['#f32f65', '#1b82c5', '#773b87','#f89c25' , '#5ca2d4' , '#98c32b', '#66addb' ]

# แสดงผลลัพธ์เป็นกราฟแท่ง
plt.bar(counts_d.index, counts_d.values,color=colors)
plt.title('ตึกไหนที่ทำให้รู้สึกไม่ปลอดภัย')
plt.xlabel('อาคาร')
plt.ylabel('จำนวน')
plt.show()

# เลือกคอลัมน์ 'ตึกไหนที่ทำให้รู้สึกไม่ปลอดภัย (เลือกได้หลายข้อ)' เท่านั้น
column_d = df['ตึกไหนที่ทำให้รู้สึกไม่ปลอดภัย  (เลือกได้หลายข้อ)']

# ลบคำว่า "ไม่มี" ออกจากคอลัมน์ 'ตึกไหนที่ทำให้รู้สึกไม่ปลอดภัย (เลือกได้หลายข้อ)'
column_d = column_d[column_d != "ไม่มี"]

# นับจำนวนของแต่ละค่าที่เหลือ
counts = column_d.value_counts()

# แยกแต่ละคอลัมน์ตาม ";" และประกอบเป็นรายการ
building_list = column_d.str.split(';')

# สร้างรายการแต่ละตึก
building_counts = []
for buildings in building_list:
    building_counts.extend(buildings)

# นับจำนวนของแต่ละตึก
counts_d = pd.Series(building_counts).value_counts()

# กำหนดสีที่ต้องการ
colors = ['#f32f65', '#1b82c5', '#773b87', '#f89c25', '#5ca2d4', '#98c32b', '#66addb']

# สร้าง Pie Chart
plt.figure(figsize=(8, 8))
plt.pie(counts_d, labels=counts_d.index, autopct='%1.1f%%', startangle=140, colors=colors)
plt.title('ตึกที่ทำให้รู้สึกไม่ปลอดภัย',pad=20)
plt.axis('equal')  # ทำให้ Pie Chart เป็นวงกลมที่แท้จริง
plt.show()

"""**ส่วนที่ 7 : ตึกต้นแบบ**"""

column_i = df['ความพึงพอใจต่ออาคารแต่ละอาคาร [บร.2]']

counts = column_i.value_counts()

# แยกแต่ละคอลัมน์ตาม ";" และประกอบเป็นรายการ
rating_list = column_i.str.split(';')
rating_list_nona = rating_list.dropna()

rating_count = []

for rating in rating_list_nona:
  rating_count.extend(rating)

rating_count

# นับจำนวนของแต่ระดับความพึงพอใจ
counts = pd.Series(rating_count).value_counts()

#กำหนดสีที่ต้องการ
colors = ['#f32f65', '#1b82c5', '#773b87','#f89c25' , '#5ca2d4' , '#98c32b', '#66addb' ]

# แสดงผลลัพธ์เป็นกราฟแท่ง
plt.bar(counts.index, counts.values,color=colors)
plt.title('ความพึงพอใจต่ออาคารแต่ละอาคาร บร.2')
plt.xlabel('ความพึงพอใจ')
plt.ylabel('จำนวน')
plt.show()

column_i = df['ความพึงพอใจต่ออาคารแต่ละอาคาร [บร.2]']

# ลบแถวที่มีค่า NaN
rating_list = column_i.dropna().str.split(';')

# สร้างรายการแต่ละระดับความพึงพอใจ
rating_count = []
for rating in rating_list:
    rating_count.extend(rating)

# นับจำนวนของแต่ระดับความพึงพอใจ
counts = pd.Series(rating_count).value_counts()

# กำหนดสีที่ต้องการ
colors = ['#f32f65', '#1b82c5', '#773b87', '#f89c25', '#5ca2d4', '#98c32b', '#66addb']

# สร้าง Pie Chart
plt.figure(figsize=(8, 8))
plt.pie(counts, labels=counts.index, autopct='%1.1f%%', startangle=140, colors=colors)
plt.title('ความพึงพอใจต่ออาคารแต่ละอาคาร บร.2',pad=25)
plt.axis('equal')  # ทำให้ Pie Chart
plt.show()

column_j = df['ความพึงพอใจต่ออาคารแต่ละอาคาร [บร.3]']

counts = column_j.value_counts()

# แยกแต่ละคอลัมน์ตาม ";" และประกอบเป็นรายการ
rating_list = column_j.str.split(';')
rating_list_nona = rating_list.dropna()

rating_count = []

for rating in rating_list_nona:
  rating_count.extend(rating)

rating_count

# นับจำนวนของแต่ระดับความพึงพอใจ
counts = pd.Series(rating_count).value_counts()

#กำหนดสีที่ต้องการ
colors = ['#f32f65', '#1b82c5', '#773b87','#f89c25' , '#5ca2d4' , '#98c32b', '#66addb' ]

# แสดงผลลัพธ์เป็นกราฟแท่ง
plt.bar(counts.index, counts.values,color=colors)
plt.title('ความพึงพอใจต่ออาคารแต่ละอาคาร บร.3')
plt.xlabel('ความพึงพอใจ')
plt.ylabel('จำนวน')
plt.show()

column_j = df['ความพึงพอใจต่ออาคารแต่ละอาคาร [บร.3]']

# ลบแถวที่มีค่า NaN
rating_list = column_j.dropna().str.split(';')

# สร้างรายการแต่ละระดับความพึงพอใจ
rating_count = []
for rating in rating_list:
    rating_count.extend(rating)

# นับจำนวนของแต่ระดับความพึงพอใจ
counts = pd.Series(rating_count).value_counts()

# กำหนดสีที่ต้องการ
colors = ['#f32f65', '#1b82c5', '#773b87', '#f89c25', '#5ca2d4', '#98c32b', '#66addb']

# สร้าง Pie Chart
plt.figure(figsize=(8, 8))
plt.pie(counts, labels=counts.index, autopct='%1.1f%%', startangle=140, colors=colors)
plt.title('ความพึงพอใจต่ออาคารแต่ละอาคาร บร.3')
plt.axis('equal')  # ทำให้ Pie Chart เป็นวงกลมที่แท้จริง
plt.show()

column_k = df['ความพึงพอใจต่ออาคารแต่ละอาคาร [บร.4]']

counts = column_k.value_counts()

# แยกแต่ละคอลัมน์ตาม ";" และประกอบเป็นรายการ
rating_list = column_k.str.split(';')
rating_list_nona = rating_list.dropna()

rating_count = []

for rating in rating_list_nona:
  rating_count.extend(rating)

rating_count

# นับจำนวนของแต่ระดับความพึงพอใจ
counts = pd.Series(rating_count).value_counts()

#กำหนดสีที่ต้องการ
colors = ['#f32f65', '#1b82c5', '#773b87','#f89c25' , '#5ca2d4' , '#98c32b', '#66addb' ]

# แสดงผลลัพธ์เป็นกราฟแท่ง
plt.bar(counts.index, counts.values,color=colors)
plt.title('ความพึงพอใจต่ออาคารแต่ละอาคาร บร.4')
plt.xlabel('ความพึงพอใจ')
plt.ylabel('จำนวน')
plt.show()

column_k = df['ความพึงพอใจต่ออาคารแต่ละอาคาร [บร.4]']

counts = column_k.value_counts()

# แยกแต่ละคอลัมน์ตาม ";" และประกอบเป็นรายการ
rating_list = column_k.str.split(';')
rating_list_nona = rating_list.dropna()

rating_count = []

for rating in rating_list_nona:
  rating_count.extend(rating)

rating_count

# นับจำนวนของแต่ระดับความพึงพอใจ
counts = pd.Series(rating_count).value_counts()

#กำหนดสีที่ต้องการ
colors = ['#f32f65', '#1b82c5', '#773b87','#f89c25' , '#5ca2d4' , '#98c32b', '#66addb' ]

# Plot the results as a pie chart
plt.figure(figsize=(8, 8))
plt.pie(counts, labels=counts.index, autopct='%1.1f%%', startangle=140, colors=colors)
plt.title('ความพึงพอใจต่ออาคารแต่ละอาคาร บร.4')
plt.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

column_m = df['ความพึงพอใจต่ออาคารแต่ละอาคาร [บร.5]']

counts = column_m.value_counts()

# แยกแต่ละคอลัมน์ตาม ";" และประกอบเป็นรายการ
rating_list = column_m.str.split(';')
rating_list_nona = rating_list.dropna()

rating_count = []

for rating in rating_list_nona:
  rating_count.extend(rating)

rating_count

# นับจำนวนของแต่ระดับความพึงพอใจ
counts = pd.Series(rating_count).value_counts()

#กำหนดสีที่ต้องการ
colors = ['#f32f65', '#1b82c5', '#773b87','#f89c25' , '#5ca2d4' , '#98c32b', '#66addb' ]

# แสดงผลลัพธ์เป็นกราฟแท่ง
plt.bar(counts.index, counts.values,color=colors)
plt.title('ความพึงพอใจต่ออาคารแต่ละอาคาร บร.5')
plt.xlabel('ความพึงพอใจ')
plt.ylabel('จำนวน')
plt.show()

column_m = df['ความพึงพอใจต่ออาคารแต่ละอาคาร [บร.5]']

counts = column_m.value_counts()

# แยกแต่ละคอลัมน์ตาม ";" และประกอบเป็นรายการ
rating_list = column_m.str.split(';')
rating_list_nona = rating_list.dropna()

rating_count = []

for rating in rating_list_nona:
  rating_count.extend(rating)

rating_count

# นับจำนวนของแต่ระดับความพึงพอใจ
counts = pd.Series(rating_count).value_counts()

#กำหนดสีที่ต้องการ
colors = ['#f32f65', '#1b82c5', '#773b87','#f89c25' , '#5ca2d4' , '#98c32b', '#66addb' ]

# Plot the results as a pie chart
plt.figure(figsize=(8, 8))
plt.pie(counts, labels=counts.index, autopct='%1.1f%%', startangle=140, colors=colors)
plt.title('ความพึงพอใจต่ออาคารแต่ละอาคาร บร.5',pad=25)
plt.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

"""**กราฟแสดงปัญหาที่มีมากที่สุดของแต่ละบร.**"""

counts_a

counts_b

counts_c

counts_d

df10 = pd.DataFrame(counts_a)
df11 = pd.DataFrame(counts_b)
df12 = pd.DataFrame(counts_c)
df13 = pd.DataFrame(counts_d)

df10.columns = ['count']

df_result = pd.merge(df10, df11, left_index=True, right_index=True)
df_result = pd.merge(df_result, df12, left_index=True, right_index=True)
df_result.columns = ['ตึกไหนบ้างที่มีปัญหาเรื่องความสะอาดของห้องเรียน (เลือกได้หลายข้อ)',
          'ตึกไหนบ้างที่มีปัญหาเรื่องความสะอาดของห้องน้ำ  (เลือกได้หลายข้อ)',
          'ตึกไหนบ้างที่มีปัญหาเรื่องความสะอาดของอาคาร  (เลือกได้หลายข้อ)']
df_result = pd.merge(df_result, df13, left_index=True, right_index=True)
df_result.columns = ['ความสะอาดของห้องเรียน',
          'ความสะอาดของห้องน้ำ',
          'ความสะอาดของอาคาร',
          'ความปลอดภัย']
df_result.plot(kind='bar',color=colors)
plt.show()

"""#WorldCloud

ติดตั้ง library
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install pythainlp

import pythainlp
from pythainlp import word_tokenize
from pythainlp.corpus import get_corpus

import wordcloud
from wordcloud import WordCloud
from wordcloud import STOPWORDS

import matplotlib.pyplot as plt
import numpy as np
import re

import pandas as pd

# %matplotlib inline
# %config InlineBackend.figure_format='ritana'

"""**ส่วนที่3 : ความปลอดภัย**

เพราะเหตุใดถึงทำให้รู้สึกไม่ปลอดภัย

บร.2
"""



"""บร.3"""



"""บร.4"""



"""บร.5"""



"""**ส่วนที่4 : ปัญหาการเดินทาง**

ปัญหาที่พบจากการใช้ทางจักรยาน
"""



"""ปัญหาที่พบจากการใช้ทางเดินเท้า"""



"""**ส่วนที่5 : ปัญหาความพร้อมของอุปกรณ์**

ความคมชัดและขนาดของเครื่องฉายสไลด์(Projector)และทีวีในห้องเรียน
"""



"""ความสมบูรณ์ของโต๊ะเรียน"""



"""ความพร้อมของคอมพิวเตอร์(บร.2)"""



"""**ส่วนที่6 : ปัญหาสิ่งอำนวยความสะดวก**

สิ่งอำนวยความสะดวกที่อยากให้เพิ่ม
"""



"""สิ่งอำนวยความสะดวกที่อยากให้ปรับปรุงแก้ไข"""

